export default {
  login: 'wkoziel',
  id: 44378819,
  node_id: 'MDQ6VXNlcjQ0Mzc4ODE5',
  avatar_url: 'https://avatars.githubusercontent.com/u/44378819?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/wkoziel',
  html_url: 'https://github.com/wkoziel',
  followers_url: 'https://api.github.com/users/wkoziel/followers',
  following_url: 'https://api.github.com/users/wkoziel/following{/other_user}',
  gists_url: 'https://api.github.com/users/wkoziel/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/wkoziel/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/wkoziel/subscriptions',
  organizations_url: 'https://api.github.com/users/wkoziel/orgs',
  repos_url: 'https://api.github.com/users/wkoziel/repos',
  events_url: 'https://api.github.com/users/wkoziel/events{/privacy}',
  received_events_url: 'https://api.github.com/users/wkoziel/received_events',
  type: 'User',
  site_admin: false,
  name: 'Wojciech Kozieł',
  company: null,
  blog: 'www.linkedin.com/in/wkoziel',
  location: 'Poland',
  email: null,
  hireable: null,
  bio: '3rd year student of CS on Silesian University of Technology',
  twitter_username: null,
  public_repos: 15,
  public_gists: 0,
  followers: 17,
  following: 13,
  created_at: '2018-10-22T19:07:14Z',
  updated_at: '2021-08-08T14:07:05Z',
}
